name = "feedback"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = ".open-next"

[vars]
NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY = "pk_live_Y2xlcmsuZmVlZGJhY2suYWN0aXZpdHl3aXouY29tJA"
NEXT_PUBLIC_CLERK_SIGN_IN_URL = "/sign-in"
NEXT_PUBLIC_CLERK_SIGN_UP_URL = "/sign-up"
NEXT_PUBLIC_R2_PUBLIC_URL = "https://pub-6b60981c500a400488efadd224143240.r2.dev"

[[d1_databases]]
binding = "DB"
database_name = "feedback-db"
database_id = "4349e88b-a871-41ab-8085-930b01fb4ffc"
migrations_dir = "drizzle"
